export const GET_TREND_MOVIES = "GET_TREND_MOVIES";
export const GET_POPULAR_MOVIES = "GET_POPULAR_MOVIES";
export const GET_POPULAR_MOVIES_BY_RELEASE_DATE =
  "GET_POPULAR_MOVIES_BY_RELEASE_DATE";

export const GET_SEARCH_MOVIES = "GET_SEARCH_MOVIES";
export const GET_GENRES = "GET_GENRES";
