export const GET_POPULAR_MOVIES = "GET_POPULAR_MOVIES";
export const GET_POPULAR_MOVIES_SUCCESS = " GET_POPULAR_MOVIES_SUCCESS";
export const GET_POPULAR_MOVIES_FAIL = "GET_POPULAR_MOVIES_FAIL";

export const GET_TOP_RATED_MOVIES = "GET_TOP_RATED_MOVIES";
export const GET_TOP_RATED_MOVIES_SUCCESS = "GET_TOP_RATED_MOVIES_SUCCESS";
export const GET_TOP_RATED_MOVIES_FAIL = "GET_TOP_RATED_MOVIES_FAIL";

export const GET_UPCOMING_MOVIES = "GET_UPCOMING_MOVIES";
export const GET_UPCOMING_MOVIES_SUCCESS = "GET_UPCOMING_MOVIES_SUCCESS";
export const GET_UPCOMING_MOVIES_FAIL = "GET_UPCOMING_MOVIES_FAIL";

export const GET_SEARCH_MOVIES = "GET_SEARCH_MOVIES";
export const GET_SEARCH_MOVIES_SUCCESS = "GET_SEARCH_MOVIES_SUCCESS";
export const GET_SEARCH_MOVIES_FAIL = "GET_SEARCH_MOVIES_FAIL";

export const GET_GENRES = "GET_GENRES";
export const GET_GENRES_SUCCESS = "GET_GENRES_SUCCESS";

export const GET_CATEGORY_MOVIES = "GET_CATEGORY_MOVIES";
export const GET_CATEGORY_MOVIES_SUCCESS = "GET_CATEGORY_MOVIES_SUCCESS";
export const GET_CATEGORY_MOVIES_FAIL = "GET_CATEGORY_MOVIES_FAIL";

export const GET_TRAILER = "GET_TRAILER";
export const GET_TRAILER_SUCCESS = "GET_TRAILER_SUCCESS";
export const GET_TRAILER_FAIL = "GET_TRAILER_FAIL";

export const GET_CAST = "GET_CAST";
export const GET_CAST_SUCCESS = "GET_CAST_SUCCESS";
export const GET_CAST_FAIL = "GET_CAST_FAIL";

export const SET_DETAIL = "SET_DETAIL";
